// SPDX-License-Identifier: MIT
import {test,expect,type Page,type Browser,type BrowserContext} from '@playwright/test';
import {ConvexHttpClient} from 'convex/browser';
import {makeFunctionReference} from 'convex/server';
import type {Session,AcceptedRoll} from '../src/client';
const backend=process.env.POWERROLLER_TEST_BACKEND??'https://nautical-partridge-636.convex.cloud';
const url='http://127.0.0.1:9590/powerroller/';
const appearance={color:'#42a5ab',ink:'#ffffff',pattern:'solid',font:'serif'};
async function namedContext(browser:Browser,name='Browser Tester',prefs:Record<string,unknown>={}):Promise<BrowserContext>{const context=await browser.newContext({viewport:{width:1280,height:800}});await context.addInitScript(({name,appearance,prefs})=>{try{if(!localStorage.getItem('powerroller.preferences.v1'))localStorage.setItem('powerroller.preferences.v1',JSON.stringify({version:1,preferences:{name,appearance,motion:'full',hidden:false,highContrast:false,announcements:'all',...prefs}}));}catch{}},{name,appearance,prefs});return context;}
async function ready(page:Page,href=url){await page.goto(href);await expect(page.getByRole('button',{name:'Roll',exact:true})).toBeEnabled();}
async function session(page:Page):Promise<Session>{return page.evaluate(()=>JSON.parse(sessionStorage.getItem('powerroller.session.v1')!));}
async function snapshot(page:Page){const s=await session(page),client=new ConvexHttpClient(backend);try{return await client.query(makeFunctionReference<'query'>('rooms:view'),{roomId:s.roomId,credential:s.credential}) as {cursor:number;latest:AcceptedRoll[]};}catch{throw new Error('Persisted room readback failed.');}}
async function configure(page:Page,mode:string,dice?:string){await page.getByRole('button',{name:'Customize dice',exact:true}).click();await page.getByLabel('Roll type',{exact:true}).selectOption(mode);if(dice)await page.getByLabel('Dice',{exact:true}).fill(dice);await page.getByRole('button',{name:'Done',exact:true}).click();}
const entries=(page:Page)=>page.locator('.roll-log-entry');
async function roll(page:Page,count:number){await page.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(page)).toHaveCount(count);return (await snapshot(page)).latest.find(r=>r.memberId===(awaitSessionMarker.get(page)))!;}
// Avoid ever printing private credentials in diagnostics or assertion operands.
const awaitSessionMarker=new WeakMap<Page,string>();
async function mark(page:Page){awaitSessionMarker.set(page,(await session(page)).memberId);}

test('two isolated clients receive one persisted power result and own clear preserves peer dice',async({browser},info)=>{
 const a=await namedContext(browser,'First Player'),b=await namedContext(browser,'Second Player');try{const one=await a.newPage(),two=await b.newPage();await ready(one);await mark(one);await ready(two,one.url());await mark(two);
 await expect(one.locator('.stage-label')).toContainText('2 / 8');await expect(two.locator('.stage-label')).toContainText('2 / 8');await one.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(one)).toHaveCount(1);await expect(entries(two)).toHaveCount(1);
 const saved=(await snapshot(one)).latest[0]!;expect(saved.source).toBe('generated');expect(saved.result.dice.map(d=>d.sides)).toEqual([10,10]);for(const page of [one,two]){await expect(page.locator('.roll-total').last()).toHaveText(String(saved.result.total));await expect(page.locator('.tier').last()).toHaveText(`Tier ${saved.result.tier}`);}
 await two.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(one)).toHaveCount(2);await one.getByRole('button',{name:'Clear my dice'}).click();await expect.poll(async()=> (await snapshot(one)).latest.map(r=>r.memberId)).toEqual([awaitSessionMarker.get(two)]);
 await one.screenshot({path:info.outputPath('desktop-two-clients.png')});
 }finally{await a.close();await b.close();}
});

test('all stock launch dice and percentiles animate and show authoritative numeric results',async({browser},info)=>{
 const context=await namedContext(browser);try{const page=await context.newPage();await ready(page);await mark(page);await expect(page.locator('.canvas-host canvas')).toBeVisible();let count=0;
 for(const sides of [3,4,6,10]){await configure(page,'sum',`1d${sides}`);await page.getByRole('button',{name:'Roll',exact:true}).click();await page.waitForTimeout(400);await page.screenshot({path:info.outputPath(`animated-d${sides}.png`)});await expect(entries(page)).toHaveCount(++count);const record=(await snapshot(page)).latest[0]!;expect(record.result.dice[0]!.sides).toBe(sides);expect(record.result.dice[0]!.value).toBeGreaterThanOrEqual(1);expect(record.result.dice[0]!.value).toBeLessThanOrEqual(sides);await expect(entries(page).last().locator('.roll-total')).toHaveText(String(record.result.dice[0]!.value));}
 await configure(page,'percentile');await page.getByRole('button',{name:'Roll',exact:true}).click();await page.waitForTimeout(400);await page.screenshot({path:info.outputPath('animated-percentile.png')});await expect(entries(page)).toHaveCount(++count);const record=(await snapshot(page)).latest[0]!,[tens,ones]=record.result.dice;const expected=(tens!.value%10)*10+ones!.value%10||100;expect(record.result.total).toBe(expected);await expect(entries(page).last().locator('.roll-total')).toHaveText(String(expected));await entries(page).last().getByText('Percentile details',{exact:true}).click();await expect(entries(page).last()).toContainText('tens');await expect(entries(page).last()).toContainText('ones');
 }finally{await context.close();}
});

test('local motion/text/contrast preferences, profile and deduplicated history survive reload',async({browser})=>{
 const context=await namedContext(browser,'Remember Me');try{const page=await context.newPage();await ready(page);await page.getByRole('button',{name:'Customize dice',exact:true}).click();await page.getByLabel('Motion',{exact:true}).selectOption('reduce');await page.getByLabel('Hide 3D dice',{exact:true}).check();await page.getByLabel('High contrast',{exact:true}).check();await page.getByLabel('Numbers',{exact:true}).selectOption('gothic');await page.getByRole('button',{name:'Done',exact:true}).click();await expect(page.locator('.canvas-host canvas')).toHaveCount(0);await page.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(page)).toHaveCount(1);const table=new URL(page.url()).searchParams.get('room');await page.reload();await expect(page.getByRole('button',{name:'Roll',exact:true})).toBeEnabled();await expect(entries(page)).toHaveCount(1);expect(new URL(page.url()).searchParams.get('room')).toBe(table);await expect(page.locator('.canvas-host canvas')).toHaveCount(0);await expect(page.locator('main.powerroller')).toHaveClass(/high-contrast/);await page.getByRole('button',{name:'Customize dice',exact:true}).click();await expect(page.getByLabel('Motion',{exact:true})).toHaveValue('reduce');await expect(page.getByLabel('Hide 3D dice',{exact:true})).toBeChecked();await expect(page.getByLabel('Numbers',{exact:true})).toHaveValue('gothic');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Open social menu'}).click();await expect(page.getByLabel('Your name',{exact:true})).toHaveValue('Remember Me');
 }finally{await context.close();}
});

test('keyboard menus restore trigger focus; enlarged and narrow views retain reachable controls',async({browser},info)=>{
 const context=await namedContext(browser);try{const page=await context.newPage();await ready(page);const customize=page.getByRole('button',{name:'Customize dice',exact:true});await customize.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog',{name:'Dice & preferences'})).toBeVisible();await page.keyboard.press('Escape');await expect(customize).toBeFocused();const social=page.getByRole('button',{name:'Open social menu'});await social.focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Close social menu'}).click();await expect(social).toBeFocused();
 // Browser zoom reflow is represented by shrinking CSS viewport to 1280/4=320px.
 // Text enlargement separately checks 200% of the inherited root font size.
 for(const [width,height,textScale,label] of [[640,400,2,'200-percent-text'],[320,200,1,'400-percent-reflow']] as const){await page.setViewportSize({width,height});await page.evaluate(scale=>{document.documentElement.style.fontSize=`${16*scale}px`;},textScale);await expect(page.getByRole('button',{name:'Roll',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await customize.click();const dialog=page.getByRole('dialog',{name:'Dice & preferences'});await expect(dialog).toBeVisible();await dialog.getByRole('button',{name:'Done',exact:true}).scrollIntoViewIfNeeded();await expect(dialog.getByRole('button',{name:'Done',exact:true})).toBeInViewport();await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.screenshot({path:info.outputPath(`${label}.png`)});}
 await page.emulateMedia({forcedColors:'active'});await customize.click();await expect(page.getByRole('dialog',{name:'Dice & preferences'})).toBeVisible();await page.keyboard.press('Escape');await expect(customize).toBeFocused();
 }finally{await context.close();}
});

test('blocked persistent storage and unavailable WebGL still permit server-generated rolls',async({browser})=>{
 const context=await browser.newContext();await context.addInitScript(()=>{for(const method of ['getItem','setItem','removeItem'] as const)Storage.prototype[method]=()=>{throw new DOMException('Storage disabled','SecurityError');};Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('Storage disabled','SecurityError');}});const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:string,...args:unknown[]){if(type.startsWith('webgl'))return null;return original.apply(this,[type,...args] as never); } as typeof original;});try{const page=await context.newPage();await ready(page);await expect(page.locator('.canvas-host canvas')).toHaveCount(0);await page.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(page)).toHaveCount(1);await expect(entries(page).last().locator('.roll-total')).toHaveText(/^\d+$/);await page.getByRole('button',{name:'Customize dice',exact:true}).click();await page.getByLabel('Hide 3D dice',{exact:true}).check();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(page)).toHaveCount(2);
 }finally{await context.close();}
});

test('concurrent and repeated identical result announcements each create a separate DOM update',async({browser})=>{
 const a=await namedContext(browser,'Same Name',{hidden:true}),b=await namedContext(browser,'Same Name',{hidden:true});try{const one=await a.newPage(),two=await b.newPage();await ready(one);await ready(two,one.url());await configure(one,'sum','1d2');await configure(two,'sum','1d2');await one.evaluate(()=>{const output:string[]=[];(window as unknown as {announcements:string[]}).announcements=output;const status=document.querySelector('[role=status]')!;new MutationObserver(()=>{const text=status.textContent?.trim();if(text)output.push(text);}).observe(status,{childList:true,subtree:true,characterData:true});});
 await Promise.all([one.getByRole('button',{name:'Roll',exact:true}).click(),two.getByRole('button',{name:'Roll',exact:true}).click()]);await one.waitForTimeout(400);await one.getByRole('button',{name:'Roll',exact:true}).click();await expect(entries(one)).toHaveCount(3);await expect(entries(two)).toHaveCount(3);await expect.poll(()=>one.evaluate(()=>(window as unknown as {announcements:string[]}).announcements.length)).toBe(3);const spoken=await one.evaluate(()=>(window as unknown as {announcements:string[]}).announcements);expect(new Set(spoken).size).toBeLessThanOrEqual(2);expect(spoken.every(text=>text.startsWith('Same Name rolled: Total'))).toBe(true);
 // DOM delivery cannot establish actual VoiceOver/NVDA spoken output.
 }finally{await a.close();await b.close();}
});
