// SPDX-License-Identifier: MIT
import { chromium } from '@playwright/test';
import fs from 'node:fs';
(async()=>{const browser=await chromium.launch();try{const results=[];for(let i=0;i<Number(process.env.RUNS||3);i++){
 const context=await browser.newContext({viewport:{width:430,height:932},hasTouch:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 if(process.env.THROTTLE){const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:150,downloadThroughput:200000,uploadThroughput:93750});await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});}
 await page.addInitScript(()=>{
  window.startup={events:[],actions:[],responses:[]};const mark=(type,detail)=>window.startup.events.push({type,at:performance.now(),detail});
  const Socket=window.WebSocket;window.WebSocket=class extends Socket{constructor(...args){super(...args);this.addEventListener('open',()=>mark('socketOpen'));this.addEventListener('message',e=>{try{const m=JSON.parse(e.data);if(m.type==='ActionResponse'||m.type==='MutationResponse')window.startup.responses.push({type:m.type,id:m.requestId,at:performance.now()});}catch{}});}send(data){try{const m=JSON.parse(data);if(m.type==='Action'||m.type==='Mutation')window.startup.actions.push({type:m.type,id:m.requestId,name:m.udfPath,at:performance.now()});}catch{}return super.send(data);}};
  let appeared=false,ready=false,canvas=false;new MutationObserver(()=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Roll');if(button&&!appeared){appeared=true;mark('buttonAppeared');}if(button&&!button.disabled&&!ready){ready=true;mark('buttonReady');}if(document.querySelector('.canvas-host canvas')&&!canvas){canvas=true;mark('canvasReady');}}).observe(document,{childList:true,subtree:true,attributes:true,attributeFilter:['disabled','aria-label']});
 });
 await page.goto(process.env.URL||'https://illos.github.io/powerroller/');await page.waitForFunction(()=>window.startup.events.some(e=>e.type==='buttonReady'),{timeout:30000});await page.waitForTimeout(300);
 const sample=await page.evaluate(()=>({...window.startup,resources:performance.getEntriesByType('resource').map(r=>({name:new URL(r.name).pathname,start:r.startTime,end:r.responseEnd,bytes:r.encodedBodySize})),navigation:performance.getEntriesByType('navigation').map(n=>({ttfb:n.responseStart,dom:n.domContentLoadedEventEnd}))}));sample.errors=errors;results.push(sample);console.log(JSON.stringify({run:i+1,events:sample.events,clock:sample.actions.filter(a=>a.name?.includes('clock')).map(a=>({start:a.at,end:sample.responses.find(r=>r.id===a.id&&r.type==='ActionResponse')?.at})),errors}));await context.close();}
 fs.writeFileSync(process.env.OUT||'/tmp/powerroller-startup-baseline.json',JSON.stringify(results,null,2));}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
